### PR TITLE
Workflows

### PR DESCRIPTION
**Pull request by xuanxu**
This PR adds all the workflows needed to use the openjournals gh-actions to be triggered by the editorial bot.

### CODE REVIEW

**Review by xuanxu — COMMENTED** [review]
cc/ @lucaferranti 
This PR supersedes #78

**Comment by lucaferranti** [comment]
@xuanxu does this have the latex compilation from https://github.com/lucaferranti/compile-action-test

**Comment by xuanxu** [comment]
No, we should next update the compilation step to use it

**Comment by xuanxu** [comment]
No, we should next update the compilation step to use it

**Pull request merged**
